GET http://localhost:8080/category HTTP/1.1
###
POST http://localhost:8080/category HTTP/1.1
Content-Type: application/json

{ "name": "Computers" }

###
GET http://localhost:8080/category/6b4c28f4-6831-495a-9444-19c93452faa3 HTTP/1.1

###
GET http://localhost:8080/product HTTP/1.1

### 
POST http://localhost:8080/product HTTP/1.1
Content-Type: application/json

{
  "name": "Product 1",
  "description": "Description 1",
  "price": 10.0,
  "category_id": "5ce585a3-fef3-427f-843b-0eadd8558230",
  "image_url": "http://localhost:9000/products/1.png"
}


###
GET http://localhost:8080/product/3f350a2a-bc9c-45c2-89da-7c2c24971d71


### 
GET http://localhost:8080/product/category/6b4c28f4-6831-495a-9444-19c93452faa3

### 
GET http://localhost:8080/product/category/7c0ca0d4-ff23-4bd7-b131-c563067c4b43
